# Generated by Django 4.2.15 on 2024-08-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='Account',
        ),
    ]
